name: Build
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 20
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: npm ci
    - name: Install React dependencies
      working-directory: react
      run: npm ci
    - run: npm run lint
    - name: Build React blocks
      run: npm run react:build
